release: remove oracle...
... it fails with the following error:

  #;sh> yum install -y git lz4-devel libuuid-devel zlib-devel

  ...

  Error: Unable to find a match: git lz4-devel libuuid-devel zlib-devel

Maybe it is missing a repository; hint:

  https://docs.oracle.com/en/operating-systems/oracle-linux/software-management/sfw-mgmt-ConfigureaSystemtoUseOracleLinuxYumServer.html